# Site settings
title: Hi, I'm Fabián
description: >
  Passionate at coding and software engineering trends. Main Java developer.
  Blogs about topics of my interest.

baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://famartin.blog.io" # the base hostname & protocol for your site

author:
  fullname: Fabián Martínez González
  github: famartinrh
  twitter: famargon13

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
markdown: kramdown